import { Liquids, Materials, RawResources, Vehicles } from "./models";

/**
 * Shared mapping of material/vehicle names to their icon names.
 * Icon names are used to generate Foxhole wiki URLs for consistent loading.
 */
export const ICONS_MAP = new Map<string, string>([
  // Materials
  [Materials.ConstructionMaterials, "ConstructionMaterialsIcon"],
  [
    Materials.ProcessedConstructionMaterials,
    "ProcessedConstructionMaterialsIcon",
  ],
  [Materials.RefinedMaterials, "RefinedMaterialsIcon"],
  [Materials.BarbedWire, "BarbedWireMaterialItemIcon"],
  [Materials.MetalBeam, "MetalBeamMaterialItemIcon"],
  [Materials.Sandbag, "SandbagMaterialItemIcon"],
  [Materials.AssemblyMaterialsI, "AssemblyMaterials1Icon"],
  [Materials.AssemblyMaterialsII, "AssemblyMaterials2Icon"],
  [Materials.AssemblyMaterialsIII, "AssemblyMaterials3Icon"],
  [Materials.AssemblyMaterialsIV, "AssemblyMaterials4Icon"],
  [Materials.AssemblyMaterialsV, "AssemblyMaterials5Icon"],
  [Materials.SteelConstructionMaterials, "SteelConstructionMaterialsIcon"],
  [Materials.ConcreteMaterials, "ConcreteBagIcon"],
  [Materials.Pipe, "EngineRoomPipeIcon"],
  [Materials.RareAlloys, "FacilityMaterials09Icon"],
  [Materials.ThermalShielding, "FacilityMaterials11Icon"],
  [Materials.UnstableSubstances, "FacilityMaterials10Icon"],
  [Materials.FlameAmmo, "FlameAmmoIcon"],

  // Liquids
  [Liquids.Petrol, "RefinedFuelIcon"],
  [Liquids.HeavyOil, "FacilityOil1Icon"],
  [Liquids.Water, "WaterIcon"],
  [Liquids.EnrichedOil, "FacilityOil2Icon"],
  [Liquids.Oil, "OilIcon"],

  // Raw Resources
  [RawResources.Salvage, "SalvageIcon"],
  [RawResources.Components, "ComponentsIcon"],
  [RawResources.Coke, "CokeIcon"],
  [RawResources.DamagedComponents, "ComponentsDamagedIcon"],
  [RawResources.Coal, "CoalIcon"],
  [RawResources.Sulfur, "SulfurIcon"],
  [RawResources.RareMetal, "RareMaterialsIcon"],
  [RawResources.HeavyExplosivePowder, "HeavyExplosiveMaterialsIcon"],

  // Vehicles
  [Vehicles.Xiphos, "ArmoredCarVehicleIcon"],
  // Armored Cars (added by PR)
  [Vehicles.Percutio, "ArmoredCarOffensiveCVehicleIcon"],
  [Vehicles.Gemini, "ArmoredCarTwinCItemIcon"],
  [Vehicles.OBrienGravekeeper, "ArmoredCarATWVehicleIcon"],
  [Vehicles.OBrienHighlander, "ArmoredCarMobilityWarVehicleIcon"],
  [Vehicles.OBrienFreeman, "ArmoredCarOffensiveWVehicleIcon"],
  [Vehicles.OBrienV110, "ArmoredCarWarVehicleIcon"],
  [Vehicles.OBrienWildJack, "ArmoredCarWarVehicleIcon"],
  [Vehicles.OBrienKnave, "ArmoredCarTwinWIcon"],
  [Vehicles.OBrienSquire, "ArmoredCarWarVehicleIcon"],
  // Field AT Rifles and Machine Guns (from main)
  [Vehicles.DuncansCoin20mm, "FieldAT2WIcon"],
  [Vehicles.GA6Cestus, "FieldAT2CIcon"],
  [Vehicles.Swallowtail, "FieldMachineGunWar"],
  [Vehicles.Sagittarii, "FieldMachineGun"],
  [Vehicles.WaspNest, "FieldMultiWItemIcon"],
  [Vehicles.Koronides, "FieldArtilleryColVehicleIcon"],
  [Vehicles.Wolfhound, "FieldCannonWVehicleIcon"],
  [Vehicles.CollinsCannon, "FieldAntiTankWarVehicleIcon"],
  [Vehicles.BatteringRam, "FieldAntiTankColVehicleIcon"],
  [Vehicles.Falconer, "FieldMortarWIcon"],
  [Vehicles.Tisiphone, "FieldMortarCIcon"],
  [Vehicles.Alekto, "LargeFieldMortarCIcon"],
  [Vehicles.Rampart, "FieldCannonOffensiveWIcon"],
  [Vehicles.Smelter, "FieldATOffensiveCIcon"],
  [Vehicles.Stockade, "FieldCannonHeavyWIcon"],
  [Vehicles.StygianBolt, "FieldATHeavyCIcon"],
  [Vehicles.Acheron, "LandingCraftVehicleIcon"],
  [Vehicles.Doru, "LandingCraftOffensiveVehicleIcon"],
  [Vehicles.MulloyLPC, "LandingCraftWarVehicleIcon"],
  [Vehicles.Actaeon, "TanketteCVehicleIcon"],
  [Vehicles.Vesta, "TanketteFlameCIcon"],
  [Vehicles.Ixion, "TanketteOffensiveCVehicleIcon"],
  [Vehicles.Deioneus, "TanketteMultiCIcon"],
  [Vehicles.Javelin, "HalfTrackColVehicleIcon"],
  [Vehicles.Hoplite, "HalfTrackColHeavyArmorVehicleIcon"],
  [Vehicles.Peltast, "HalfTrackArtilleryCIcon"],
  [Vehicles.NiskaMkI, "HalfTrackWarVehicleIcon"],
  [Vehicles.NiskaMkII, "HalfTrackOffensiveWarVehicleIcon"],
  [Vehicles.NiskaMkIII, "HalftrackTwinW"],
  [Vehicles.NiskaRyckerMkIX, "HalftrackMultiWIcon"],
  [Vehicles.KingSpireMkI, "ScoutTankWIcon"],
  [Vehicles.KingJesterMkI1, "ScoutTankMultiWIcon"],
  [Vehicles.KingGallantMkII, "ScoutTankOffensiveWIcon"],
  [Vehicles.H5Hatchet, "LightTankColVehicleIcon"],
  [Vehicles.H10Pelekys, "LightTankOffensiveCVehicleIcon"],
]);
